"""add likes table and likes_count

Revision ID: 559bef2b36d4
Revises: f7d9d3c12d11
Create Date: 2026-07-23 19:47:56.021213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559bef2b36d4'
down_revision: Union[str, Sequence[str], None] = 'f7d9d3c12d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('likes_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoughts', 'likes_count')
    # ### end Alembic commands ###
