"""add user_id to thoughst

Revision ID: e6d9cca78c6b
Revises: 
Create Date: 2026-07-20 19:11:14.679993

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e6d9cca78c6b'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('user_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'thoughts', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'thoughts', type_='foreignkey')
    op.drop_column('thoughts', 'user_id')
    # ### end Alembic commands ###
