"""add created_at to thoughts

Revision ID: f7d9d3c12d11
Revises: e6d9cca78c6b
Create Date: 2026-07-21 18:21:54.338340

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f7d9d3c12d11'
down_revision: Union[str, Sequence[str], None] = 'e6d9cca78c6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('thoughts', sa.Column('created_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('thoughts', 'created_at')
    # ### end Alembic commands ###
